### PR TITLE
Correct a cast in winfsp_fuse

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR corrects the cast issue in winfsp_fuse.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by billziss-gh** [comment]
@benrubson thank you for the PR. I will also have to rebuild FUSE for Cygwin for x64 and x86 (in `opt/cygfuse`) after we incorporate your change.

In order for me to accept contributions to this project I require that you add your name and email address to the Contributors document: https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc

This effectively signs the document, assigns joint copyright to your change and identifies you as a contributor. You only need to do this one time on your first contribution.

Re: tests failing. This does not appear related to your changes. Unfortunately drives fail to mount in the alloted time in recent builds; this is not something that is related to your changes.

**Comment by benrubson** [comment]
Thank you Bill, document just filled-in 👍

**Comment by billziss-gh** [comment]
Your PR has been merged. Thank you for your contribution :)

**Comment by benrubson** [comment]
A tiny one :) Thank you for merging 👍

**Comment by billziss-gh** [comment]
Unfortunately this change does not allow me to build cygfuse. The issue is that Cygwin has a prototype for `void *cygwin_create_path(...)` which conflicts with out definition of `char *cygwin_create_path(...)`.

I am changing this to the following:

```C
static inline char *fsp_fuse_conv_to_win_path(const char *path)
{                                                              
    void *cygwin_create_path(unsigned, const void *);          
    return (char *)cygwin_create_path(                         
        0/*CCP_POSIX_TO_WIN_A*/ | 0x100/*CCP_RELATIVE*/,       
        path);                                                 
}                                                             
```

Can you please verify that it allows you to compile EncFS without problems?

**Comment by benrubson** [comment]
Sorry for this :/
Just tested with your modification, if works perfectly 👍

**Comment by billziss-gh** [comment]
No problem. Thanks for testing. New commit in a few secs with all the changes included.

**Comment by billziss-gh** [comment]
Commit 1cab0f39751093fca4513601a9db2f7bbc09c776 should address this.

**Pull request merged**
