### PR TITLE
Fixed invalid Sid bug

### PR DESCRIPTION
**Pull request by sganis**
Add support for domains with large number of users, to address bug #199 
----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [x] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [x] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

**Comment by billziss-gh** [comment]
In my comments below please note that I am currently lacking all the context that I had when I was initially writing this code.

----

Can you please explain this PR a bit more? I do not understand how your change fixes a problem. Perhaps it fixes a problem in your environment, but it could create problems in other environments?

The tests in that code are based on this document: https://cygwin.com/cygwin-ug-net/ntsec.html and the Cygwin code here:

https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/uinfo.cc;h=bfcce00da03e4c96630053a0eb206bcb17fd7615;hb=HEAD#l2239

Perhaps the problem you are experiencing is that WinFsp does not currently fully implement support for domain users. For example, it does not implement `trustPosixOffset`. In that case the real fix may be to implement those (although I do not have access to such a complex Windows domain environment and it would be hard to implement correctly).

**Comment by sganis** [comment]
Sure,
All my users belong to the same primary domain, and users with RID > 0x200000 (2097152 in decimal) get a null SID because the code is assuming any RID larger that that number belongs to a trusted domain, which is not implemented as you say. I have a lot of users in this situation, and new accounts too, as active directory auto increments the account RID. 
I couldn't find any documentation about that range, and the cygwin reference does mention the 0x200000 limit.
I don't think this PR will cause issues in other environments, it's just considering any RID in the range 0x200000-0x300000 to be in the primary domain too, and not return a null SID.
I know my case is extreme, but it is the simplest solution so far.
I tried to install my modified version, but windows complains about the signature in the sys file. I also tried to replace the winfsp-x64.dll which is not signed, but I can't do it in corporate machines without an installer. One last resource could be to create an installer with the .dll and your signed .sys, but I didn't try this option.

**Comment by billziss-gh** [comment]
I am not opposed to your change as it seems to solve a real-world problem for you. I just want to
make sure that we do the right thing.

The current Cygwin sources use `UNIX_POSIX_OFFSET==0xff000000` as the upper limit for determining domain accounts. Perhaps we should use that as the upper limit instead of `0x300000`? Cygwin appears to use that as the upper limit when it cannot find any `trustPosixOffset`.

BTW, I am assuming that no change is needed in `FspPosixMapSidToUid`? From my review of this code it does not seem that anything is needed, but I would like to confirm. The reason is that
`FspPosixMapSidToUid` and `FspPosixMapUidToSid` are supposed to be a bijective mapping (or as close to that as possible).

Finally for me to accept a change you would have to add your name to the [Contributor Agreement](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). This would signify acceptance of its terms.

**Comment by sganis** [comment]
An upper limit of 0x300,000 would support primary domains of 2M+ users, or even 0x400,000, but I think the number 0xff000000 is too big and risky.
I agree with the rest of your comments.

**Comment by billziss-gh** [comment]
@sganis sorry for the long delay. I was away for a few days.

I will merge your PR in, but will likely update the limit to be `0xff000000`. This is because my understanding of the Cygwin code goes something like this.

```C
      else if (arg.id < PRIMARY_POSIX_OFFSET/*0x00100000*/)
        // ...
      else if (arg.id == ILLEGAL_UID/*(uid_t)-1*/)
        // ...
      else if (arg.id >= UNIX_POSIX_OFFSET/*0xff000000*/)
        // ... NFS or SAMBA
      else /* 0x00100000 <= arg.id && arg.id < 0xff000000 */
        {
          // ...
          if (/*...*/)
            // ...
          else /* <<no trusted domain>> && 0x00100000 <= arg.id && arg.id < 0xff000000 */
            {
              /* Primary domain */
              csid = cygheap->dom.primary_sid ();
              csid.append (arg.id - PRIMARY_POSIX_OFFSET/**/);
            }
          // ...
        }
```

**Comment by billziss-gh** [comment]
@sganis this has now been merged in. Thank you very much for your contribution.

**Comment by billziss-gh** [comment]
@sganis WinFsp 2019.3 B1 is out. It includes the discussed changes.

**Pull request merged**
