### PR TITLE
Make FlushAndPurgeOnCleanup accessible in C++

### PR DESCRIPTION
**Pull request by colatkinson**
I was running into the same issue as #206, and realized this option wasn't accessible via the C++ bindings. I also went ahead and set this option to `TRUE` in the passthrough-cpp system, in order to better align with the behavior of the C passthrough.

----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [x] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [x] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

**Comment by colatkinson** [comment]
I'm not sure whether the test that failed is known to be flaky, but I don't see how these changes would have affected it. If I'm mistaken, please let me know.

**Comment by billziss-gh** [comment]
@colatkinson thank you for this PR.

The PR looks fine and I will be happy to accept it. The test that failed is not relevant to your PR as it is not related to the C++ layer. Although I have not seen this particular failure before it looks like it is related to file deletion, which is unfortunately a common occurrence in the Windows file system. (Files in Windows do not get deleted until all file handles are gone and often system components open soon-to-be-deleted files for their own purposes thus increasing the handle count.)

For me to accept the PR you will also have to sign the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). Simply add your name to the list in the document if you agree; we currently use *Firstname Lastname* alphabetical ordering. You will only have to do this for your first contribution.

Finally please keep in mind that I do not currently test the C++ layer. For proper testing of the layer we would need to port the MEMFS layer to C++ and then pass all winfsp-tests and Microsoft's IfsTest.

**Comment by colatkinson** [comment]
I've signed the CLA. As for testing of the C++, that makes sense--from what I've gathered it seems to be a somewhat secondary concern. If I ever have a spare weekend, maybe I'll try porting memfs over.

Let me know if you have any other questions w.r.t. the PR.

**Comment by billziss-gh** [comment]
This is curious. The same test failed on a FUSE sample again. This is something I definitely need to look at.

In any case I do not believe this is related to your change and I will therefore merge your PR. Thank you again for your contribution.

**Pull request merged**
