### PR TITLE
Slowio : The ability to delay and postpone io for testing and as a STATUS_PENDING example

### PR DESCRIPTION
**Pull request by JohnOberschelp**
All changes marked with "Slowio"
Do nothing, and memfs will not change behavior.
Use 3 new command line parameters to delay and postpone io.
For example ...
`-M 1000 -D 30 -R 12`
... will ...
Add up to a 1000ms delay to effected io; those are Read, Write, and ReadDirectory
Postpone 30% of effected io by forking a thread and returning STATUS_PENDING
Reduce the likelihood of long delays by decreasing them by up to 12 bits

### CODE REVIEW

**Comment by billziss-gh** [comment]
Looking into this now. Sorry for the delay.

**Comment by billziss-gh** [comment]
Thank you very much for the PR. My comments below:

- WinFsp uses a 4 space indentation and no tabs. Please make sure that no tabs are used.

- Please add a `MEMFS_SLOWIO` macro at the beginning of `memfs.cpp`. Then make all "Slowio" code conditionally compiled within `memfs.cpp`.
    - You may notice that I do this with some other MEMFS features (e.g. named streams). It is useful to me to be able to test MEMFS without some functionality at times. This could also allow me to exclude this functionality from `NDEBUG` builds, for benchmarking purposes, etc.
    - `MemfsCreateFunnel` creates a small problem in that it would take a different number of parameters depending on whether `MEMFS_SLOWIO` is defined or not. We can add the extra parameters to it (regardless of `MEMFS_SLOWIO`), but have them do nothing when `MEMFS_SLOWIO` is not defined.
    - I also recommend that the `MemfsCreate` macro parameters are not changed, but simply pass `0, 0, 0` for the new parameters. This will eliminate the changes on `fscrash-main.c` and `memfs-test.c`.

- Although in general I prefer the standard C types (e.g. `uint64_t`), since this project is a low-level Windows project I chose to use Windows types such as `UINT64`. My preference is that we stick to those for consistency with the rest of the code. [I often break this rule in the FUSE layer.]

- For consistency again I would prefer names to follow the conventions of the rest of the code. E.g. `PseudoRandom` vs `pseudoRandom`.

- There are a few style issues that are not easy to communicate without a complete style guide. I will fix those later.

- `pseudoRandom`: This function is interesting; I would like to hear more about it! Taking the hash of a counter is akin to a crypto method. In any case I think we should make it threadsafe (e.g. by using `InterlockedIncrement` on the `seed`).

- `SlowioShouldPostpone`: Should probably have a quick exit when `SlowioPercentDelay==0`. As you know I also use MEMFS for benchmarking and would like to minimize unnecessary delays.

- `SlowioMillisecondsOfDelay`: The intent of `pseudoRandom(SlowioMaxDelay) >> pseudoRandom(SlowioRarefyDelay)` was not immediately obvious to me, but I believe that the intent is to make fast "slowio" more likely than slow "slowio". Is that correct?
    - I believe this would crash if `SlowioRarefyDelay` is 0(?).

- `ioThreadsRunning`: Should be a field in `struct _MEMFS` (and perhaps renamed to `SlowioThreadsRunning`). Under the current scheme of checking it in a loop during `MemfsStop`, I agree that it should be `volatile`. However we may have to improve on this.

- `readThread`, `writeThread`, `readDirectoryThread`:
    - Should be renamed `SlowioReadThread` and `SlowioWriteThread`, etc.
    - Is there a particular reason to use `std::this_thread::sleep_for` vs Windows `Sleep`, which you use elsewhere?
    - It is probably safe to access `FileNode` without a lock because the FSD maintains a lock per file that it acquires shared during `Read` and `ReadDirectory` and exclusive during `Write`. But I must think about this a bit more and make sure there is not a gotcha I have not thought of. To be on the safe side you may want to move the `memcpy` into the original `Read` and `Write` calls. [OTOH leaving them here will force me to think this through :) ]
    - I believe that `ioThreadsRunning` should be incremented before the new thread starts running (i.e. in `Read`, `Write`, etc.) Consider that a thread is created in `Read`, but then the file system is terminated by the user (e.g. Ctrl-C) before the thread starts running. `MemfsStop` runs and finds no threads so it completes and then `MemfsDelete` happily deallocates the world, at which time the OS decides to run the delayed thread...

- `Read`, `Write`, `ReadDirectory`:
    - I am a bit uncomfortable with `std::thread` primarily because it may throw; I probably would have been more comfortable with `CreateThread`. It is true that I use `std::map` already and I also use `new`, which may throw `bad_alloc`; unfortunately I had no choice there since C does not have an ordered map data structure. But `std::thread` may throw `system_error` [[link](http://en.cppreference.com/w/cpp/thread/thread/thread)] and MEMFS was not written with the ability to recover from exceptions. At the very least we should capture the exception and probably complete the I/O in the normal manner (i.e. without `STATUS_PENDING`).
    - As mentioned `ioThreadsRunning` should be incremented prior to thread creation. It should be decremented if thread creation fails.
    - I do not think we should sleep if `SlowioShouldPostpone` fails.

- `MemfsStop`: The `ioThreadsRunning` loop should be after the `FspFileSystemStopDispatcher` call. This call guarantees that all dispatcher threads (i.e. the threads were you get calls like `Read`, `Write`, etc.) have terminated and you will not receive additional file system operation calls. Otherwise it is possible for the `ioThreadsRunning` loop to complete, only to receive an additional `Read` call that spawns a new thread just prior to the dispatcher being stopped.
    - The `ioThreadsRunning` loop (together with `volatile`) is not ideal, but should work and would be adequate for a first pass. We may have to improve on this later by using a manual reset event that gets set/reset based on the condition `ioThreadsRunning==0` or similar mechanism.

- `Contributors.asciidoc` document: For me to accept this PR I also request that contributors add their name to the `Constributors.asciidoc` document. This assigns joint copyright to the changes in your PR to both of us and identifies you as a contributor to this project. You only need to do this once and will not need to do it again if you decide to send additional PR's.

Thank you again for your work on this. It is late where I am, so I will stop for now and will probably do another review pass tomorrow.

**Comment by JohnOberschelp** [comment]
Oops! I am new to PRs; I was waiting for your response on...
`https://github.com/billziss-gh/winfsp/issues/108`
… and not here, on...
`https://github.com/billziss-gh/winfsp/pull/110`
!

All your comments are clear and spot on. I will implement and resubmit.

You asked about `PseudoRandom()`:
I wrote it after thinking about simple generators; it occurred to me (though I am sure someone else has done this before) that I could increment a value and the hash of it would be my next pseudorandom value.

**Comment by billziss-gh** [comment]
@JohnOberschelp, no problem :)

Re: `PseudoRandom`.

It is an interesting method and somewhat reminiscent of the techniques described in [SP 800-90A](https://csrc.nist.gov/publications/detail/sp/800-90a/rev-1/final), especially CTR_DRBG (which uses a block cipher). [Disclaimer: I am not expert or even proficient in such matters.]

NIST also has a test suite for RNG's ([link](https://csrc.nist.gov/Projects/Random-Bit-Generation/Documentation-and-Software)) if you ever want to test/improve your RNG.

Related stackoverflow article: https://crypto.stackexchange.com/questions/9076/using-a-hash-as-a-secure-prng#9080

**Comment by JohnOberschelp** [comment]
OK. If I understand well enough and have updated files correctly, here is my revised PR.

Outside of just implementing your suggestions:

- I renamed `SlowioShouldPostpone` to `SlowioReturnPending`, as that name ties it to `STATUS_PENDING`, and doesn’t introduce the new verb “postpone”.

- You asked “The intent of… `SlowioRarefyDelay` ...is to make fast "slowio" more likely than slow "slowio". Is that correct?”
Yes. I use it so that I can have long delays crop up every once in a while, while keeping most delays relatively shorter.

- You said “I do not think we should sleep if `SlowioShouldPostpone` returns `FALSE`.”
This is your call of course, but I think I/O delays outside of a `STATUS_PENDING`, plain old slow responses, are a real thing to model, so I left them in for your reconsideration.

I apologize in advance if I missed or misinterpreted any of your comments and thank you in advance for volunteering to tidy up style issues. And BTW, I am using GitHub WAY wrong. Gotta work on that. Hope my floundering did not interfere with this PR.

**Comment by JohnOberschelp** [comment]
Also, I updated `Contributors.asciidoc` locally, but I see it did not make it to the PR. Investigating...

**Comment by billziss-gh** [comment]
@JohnOberschelp thanks for the update. I should be able to check the updated PR later today.

I notice that the build check failed, but it does not appear to be related to your changes. Builds have been slightly flaky lately and I am wondering if they are related to some changes I made recently in "QueryDirectory" handling, although it is not obvious why.

**Comment by billziss-gh** [comment]
I have done a preliminary review of the PR updates. Looks very good. Thank you!

> You said “I do not think we should sleep if SlowioShouldPostpone returns FALSE.”
This is your call of course, but I think I/O delays outside of a STATUS_PENDING, plain old slow responses, are a real thing to model, so I left them in for your reconsideration.

On further reflection I agree with you. Let's leave them in.

I do have a question though: in your reimplementation of `Read`, `Write` and `ReadDirectory` you do something along the lines of:

```C++
#ifdef MEMFS_SLOWIO
    int ms = SlowioMillisecondsOfDelay(FileSystem);
    if (ms) Sleep(ms); 
    if (SlowioReturnPending(FileSystem))
    {
        // ...
        return STATUS_PENDING;
    }
regular:
```

Does that not mean that there is now the potential for two sleeps? One is before the `SlowioReturnPending` check and one if the check succeeds and we spawn a thread. Is this desirable?

This looks to me more logical. Or did I miss or misunderstand something?

```C++
#ifdef MEMFS_SLOWIO
    if (SlowioReturnPending(FileSystem))
    {
        // ...
        return STATUS_PENDING;
    }
regular:
    int ms = SlowioMillisecondsOfDelay(FileSystem);
    if (ms) Sleep(ms); 
```

> I apologize in advance if I missed or misinterpreted any of your comments and thank you in advance for volunteering to tidy up style issues. And BTW, I am using GitHub WAY wrong. Gotta work on that. Hope my floundering did not interfere with this PR.

I think you understood my comments very well and thank you for accommodating them.

Re: GitHub. No problem :) I understand where you are coming from. I also do not find all GitHub workflows obvious/intuitive, especially concerning PR's.

----

I will do a second review pass and then merge into a private branch to fix some stylistic issues, resolve some conflicts and then test. Once this is done I will merge with master.

**Comment by billziss-gh** [comment]
I have merged your changes into the [pvt-slowio](https://github.com/billziss-gh/winfsp/tree/pvt-slowio) branch. I will test them locally and with AppVeyor and then merge into [master](https://github.com/billziss-gh/winfsp/tree/master).

Unfortunately AppVeyor builds have been fragile in the last few days and I am not sure why. As mentioned there was a major change in how "Query Directory" is handled, however I got a few green builds after that change was introduced and before builds started going red. This may mean that it may be related to a change in the AppVeyor environment, etc.

I need to figure out what the problem is and resolve it. I am also away next week, so probably it will be a couple of weeks before I manager to merge this into [master](https://github.com/billziss-gh/winfsp/tree/master).

**Comment by billziss-gh** [comment]
@JohnOberschelp I have been able to test your `STATUS_PENDING` changes with `winfsp-tests` and `fsx` and I am fairly confident that things work as should. I have merged your changes into the master branch. Thank you again for the great work!

**Comment by JohnOberschelp** [comment]
Thank you. You are very easy to work with. Just FYI, the double delay was intentional, but obviously minor. And "Snooze" is a great word.

**Pull request merged**
