### PR TITLE
Avoid creating unncessary permissions (almost empty permissions)

### PR DESCRIPTION
**Pull request by jeaneric**
This is to solve a bug in [rclone-4717](https://github.com/rclone/rclone/issues/4717) when mounting encrypted data. This was logged in rclone, but when further analyzed, all the correction has to be done in winfsp.

In brief the bug was that for a mask 700 when mouting, winfsp created basic permissions for groups and everyone that cause a bug when using for storing keys used by openssh.

This pull request ensure that when everyone (world) and/or group don't have ANY permission, so winfsp don't add the basic perms it define.

I have compiled and tested and it worked as expected on my test machine.

----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [ ] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [ ] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [ ] **Quality**: Your design and code should be of high quality and something that you are proud of.

I'm not a C programmer, so I won't judge the Quality of the code I add, even if very simple... I just hope it's ok.

### CODE REVIEW

**Comment by ivandeex** [comment]
@billziss-gh Please review

**Comment by billziss-gh** [comment]
Looking at this now.

**Comment by billziss-gh** [comment]
@jeaneric thank you very much for your work and apologies that I took so long to look into it in detail.

Unfortunately I cannot accept this PR. I explain below my reasons. I also often an alternative that hopefully addresses the original reason for this PR in rclone/rclone#4717.

## Reasons for not accepting this PR

The PR changes the default Windows permissions that the UNIX file "owner", "group" or "world" have. Unfortunately removing these permissions is problematic:

- The default permissions are specified by the SFU specification which WinFsp follows to map UNIX permissions to security descriptors and vice-versa.

**Comment by jeaneric** [comment]
@billziss-gh , ok, I'm gone a take a look at the solution soon. I don't know anything about the default posix permissions so that's ok with me.

Thanks for taking the time to look into this and offer an alternate solution.

**Pull request closed without merging**
