### PR TITLE
Async I/O for dotnet

### PR DESCRIPTION
**Pull request by dworkin**
Add asynchronous I/O support for Read, Write and ReadDirectory.
----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [x] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [x] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

**Comment by dworkin** [comment]
```
3293 === Running fsx-memfs-dotnet-slowio
3294 The operation completed successfully.
3295 The operation completed successfully.
3296 The operation completed successfully.
3297 The operation completed successfully.
3298 net use L: "\\memfs.net-slowio\share"
3299 The command completed successfully.
3300
3301 net use | findstr L:
3302              L:        \\memfs.net-slowio\share  WinFsp.Np
3303 Using file test
3304 command line: C:\projects\winfsp\ext\test\fstools\src\fsx\fsx.exe -N 5000 test       
3305 Seed set to 1559667395
3306 truncating to largest ever: 0xd74c
3307 truncating to largest ever: 0x35f80
3308 truncating to largest ever: 0x40000
3309 All operations - 5375 - completed A-OK!
3310 net use L: /delete
3311 L: was deleted successfully.
3312
3313 The operation completed successfully.
3314 === Passed fsx-memfs-dotnet-slowio
```

**Comment by billziss-gh** [comment]
@dworkin thank you for your PR and double thank you for adding tests! From a brief look it looks great. I am hoping to thoroughly review it before the end of the week.

BTW, why did you need to make `SeekableReadDirectory` virtual? Any chance that this could be a breaking change for file systems that use `SeekableReadDirectory`? Also should we also make `BufferedReadDirectory` virtual for symmetry?

**Comment by dworkin** [comment]
@billziss-gh I should not have made SeekableReadDirectory virtual.  I see that SeekableReadDirectory is called from ReadDirectory, which is already virtual.  So I should just have overridden ReadDirectory.

**Comment by billziss-gh** [comment]
@dworkin the changes in `src/dotnet` look correct.

Unfortunately I was able to make `memfs-dotnet` crash with the `MEMFS_SLOWIO` changes. The problem is that it is possible for a Slowio task to be in flight when `OnStop` is called. `OnStop` executes `Host.Unmount`, which first does `FspFileSystemStopDispatcher`, then `FspFileSystemDelete` and then sets `_FileSystemPtr` to 0.

If part of a Slowio task executes after the file system is deleted and the `_FileSystemPtr` is set to 0, it is possible to get an access violation:

av

Call stack:
cs

Variables:
vars

I think we could get around this problem by waiting for tasks to complete in an `Unmounted` override (which is executed from within `Host.Unmount` after `FspFileSystemStopDispatcher`, but prior to `FspFileSystemDelete`. Is there an easy way to wait for all tasks to complete in .NET?

(The C++ version of MEMFS uses a simple mechanism to handle this. It maintains a count of Slowio tasks/threads in a `SlowioThreadsRunning` variable. Then when the file system is stopped it first calls `FspFileSystemStopDispatcher` and then waits for `SlowioThreadsRunning` to become 0 in a `Sleep` loop. Rather crude but it works.)

If you do not have the time to look into this I can still accept your PR, but can only include your changes in `src/dotnet`. I will temporarily remove your changes in `memfs-dotnet` and revisit this myself at a later time.

Let me know how you would like to proceed.

----

I include instructions to reliably cause the file system to crash while running under the debugger.

- Change `SlowioSnooze` to always perform a `Thread.Sleep(10000)`.
- Place a breakpoint at `SlowioReadDirectoryTask`.
- Place a breakpoint at `OnStop`.
- Launch the file system with debug arguments: `-i -F NTFS -M 50 -P 10 -R 5 -m Y:`
- In a command prompt switch to the Y: drive and keep creating files/directories and issuing `dir`. For example: `echo hello>world`, `dir`, `mkdir foo`, `dir`, etc. The breakpoint usually triggers fairly fast.
- When the `SlowioReadDirectoryTask` breakpoint triggers let it run into `SlowioSnooze` and while the thread is sleeping, switch to the file system window and press Ctrl-C.
- When the `OnStop` breakpoint triggers, step over `Host.Unmount` and then freeze the thread.
- Continue the program and you should now see the attached access violation.

**Comment by dworkin** [comment]
@billziss-gh I will fix `memfs-dotnet` and push a new version within the next few days.

**Comment by dworkin** [comment]
@billziss-gh I followed your suggestion and copied code from `memfs.cpp` almost verbatim.

```
3373 === Running fsx-memfs-dotnet-slowio
3374 The operation completed successfully.
3375 The operation completed successfully.
3376 The operation completed successfully.
3377 The operation completed successfully.
3378 net use L: "\\memfs.net-slowio\share"
3379 The command completed successfully.
3380
3381 net use | findstr L:
3382             L:        \\memfs.net-slowio\share  WinFsp.Np
3383 Using file test
3384 command line: C:\projects\winfsp\ext\test\fstools\src\fsx\fsx.exe -N 5000 test       
3385 Seed set to 1561044437
3386 truncating to largest ever: 0x174a4
3387 truncating to largest ever: 0x1e174
3388 truncating to largest ever: 0x40000
3389 All operations - 5334 - completed A-OK!
3390 net use L: /delete
3391 L: was deleted successfully.
3392
3393 The operation completed successfully.
3394 === Passed fsx-memfs-dotnet-slowio
```

But then:

```
Build execution time has reached the maximum allowed time for your plan (90 minutes).
Change boot configuration and reboot
```

**Comment by billziss-gh** [comment]
> I followed your suggestion and copied code from memfs.cpp

Thank you.

> Build execution time has reached the maximum allowed time for your plan

Unfortunately sometimes AppVeyor is flaky. It looks like the AppVeyor VM never came back from the reboot that is done to turn off test-signing. Completely unrelated to your changes.

**Comment by billziss-gh** [comment]
I have merged this PR into master. Thank you for your excellent work in this and for accommodating my requests.

**Comment by dworkin** [comment]
@billziss-gh Thank you for the discussion here and with [issue 230](https://github.com/billziss-gh/winfsp/issues/230), it has been extremely helpful.

**Pull request merged**
