### PR TITLE
Remove "FUSE-" prefix from file system name when using FUSE API

### PR DESCRIPTION
**Pull request by johntyner**
This change addresses issue #250 by adding a `-E`/`--ExactFileSystemName` option which sets the visible file system name/type to that specified on the command line. This differs from the `-F`/`--FileSystemName` option in that the latter prepends "FUSE-" to the specified file system name where the former does not.

I considered a `-R`/`--RawFileSystemName`, but given the near-ubiquitous use of `-r`/`-R` to mean "recursive" or similar, I thought it might create confusion and went with the [suggestion](https://github.com/billziss-gh/winfsp/pull/251#issuecomment-536215888) of "E"/"Exact".

----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/billziss-gh/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [x] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [ ] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

**Comment by billziss-gh** [comment]
@johntyner thank you.

I have thought about this some more and although the PR is exactly what I would have done to solve this problem in the way discussed in #250, I cannot accept it as is. I want to apologize for this change of opinion and explain why this is so.

The primary reason is **backwards compatibility**, which is very important for the WinFsp project. With this PR we are changing the meaning of the `--FileSystemName` and `-o fstypename` switches in a way that existing file systems did not anticipate. For example there may be an XxxFs file system out there that fully expects its file system name to be `FUSE-XxxFs` when passing the `--FileSystemName=XxxFs` switch; such a file system could break with this PR.

(There is a secondary reason: file system identification. The reason that the `FUSE-` prefix was added is that such file systems could be easily identified; especially because they advertise themselves as supporting Windows ACL's, but in practice they only support what can be emulated via UNIX uid, gid and permission bits.)

So I propose an alternative switch `--ExactFileSystemName` that does what you want. (Suggestions for a better name than `--ExactFileSystemName` are welcome.) Such a switch would alleviate my main concern, which is **backwards compatibility**.

Please let me know what you think, before we proceed with this. Again I apologize for asking you to submit a PR that does exactly what you did and then changing my opinion. If you are unwilling to change the PR because I am asking you to do double work, I can also look into this myself.

**Comment by johntyner** [comment]
No worries at all, @billziss-gh. I think your concerns for backward compatibility and about the ACLs vs POSIX permissions are well placed.

It'll take me a day or two to come back to this, but I'll make the changes. I'll mention you in a comment here when I get the changes posted.

**Comment by billziss-gh** [comment]
@johntyner thanks again for the understanding.

I expect that the following steps would be needed for the updated PR:

- Two `FUSE_OPT_KEY` options would have to be added [here](https://github.com/billziss-gh/winfsp/blob/v1.5B2/src/dll/fuse/fuse.c#L103-L104) along the pattern that is currently used for `FileSystemName`. The key used must be unique (e.g. `'E'` if you decide to use `ExactFileSystemName`).
- A new `case 'E'` to handle the new options [here](https://github.com/billziss-gh/winfsp/blob/v1.5B2/src/dll/fuse/fuse.c#L355). You can model it similar to the code that you have submitted for `FileSystemName` in this PR.
- There should not be any additional code changes necessary.

**Comment by johntyner** [comment]
Suggested changes have been made, @billziss-gh. Thanks for waiting while I had to deal with my day job.

**Comment by billziss-gh** [comment]
@johntyner, I am merging this PR. Thank you for taking the extra time to make the changes I requested.

**Pull request merged**
